
services:
  fictional-public-library:
    build:
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    environment:
      MONGO_URI: "mongodb://mongo:27017/"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - storage:/data/db/mongo

volumes:
  storage: